// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwiueyaruahpkftludco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aXVleWFydWFocGtmdGx1ZGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDA5MjgsImV4cCI6MjA2NjM3NjkyOH0.n0ZFLOe2OpU6j1eUciCRd_3DdxTcm2KfClZ1K46Hr38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);